name: "Build Firmware"
description: "Build Firmware"
inputs:
  makearg:
    description: "Arguments to pass for make"
    required: false
    default: "defconfig all size-components"
runs:
  using: "docker"
  image: "./Dockerfile"
  args:
    - ${{ inputs.makearg }}
