# This is a basic workflow to help you get started with Actions

name: Docker

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Building docker image
        run: |
          IMAGE_ID=nsfilho/esp8266-rtos-sdk
          VERSION=3.3
          docker build --rm=true --force-rm=true -t $IMAGE_ID:$VERSION ./
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_STORE_PASSWORD }}" | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_STORE_USERNAME }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=nsfilho/esp8266-rtos-sdk
          VERSION=3.3
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker push $IMAGE_ID:$VERSION
